version: "3"
services:
  train_center:
    build:
      context: . 
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/workspace
      - ../dataset:/dataset
    devices:
      - /dev/video0:/dev/video0
    stdin_open: true
    tty: true